# Generated by Django 5.0.6 on 2024-06-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_isbn_book_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='parent',
        ),
    ]
