# Generated by Django 5.0.6 on 2024-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookelement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
