# Generated by Django 5.0.6 on 2024-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookelement_language'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='categories.category'),
        ),
    ]
